version: '3'

services:
  wordpress:
    image: wordpress:latest
    volumes:
      - wordpress:/var/www/html
      - themes:/var/www/html/wp-content/themes
    environment:
      WORDPRESS_DB_HOST: "db"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: "password"
      WORDPRESS_DEBUG: "true"
    depends_on:
      - database
  database:
    image: mariadb:latest
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--max_allowed_packet=256M',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_520_ci'
        ]
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: "password"

volumes:
  themes: