version: '3'
services:
  wordpress:
    build: ./
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    links:
      - db
    volumes:
      - wordpress:/var/www/html
      - .:/workspace
      # - ../plugin-dev:/var/www/html/wp-content/plugins/plugin-dev
      - ../theme-dev:/var/www/html/wp-content/themes/theme-dev

  db:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql

  mailhog:
      image: mailhog/mailhog:latest
      container_name: myapp-mailhog
      ports:
        - "8003:1025"
        - "8100:8025"

volumes:
  wordpress:
  data: